apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: pod-terminator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-terminator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-terminator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-terminator
subjects:
  - kind: ServiceAccount
    name: pod-terminator
    namespace: default
